--zad1
CREATE TABLE A6_LRS (
GEOM MDSYS.SDO_GEOMETRY);

--b
insert into A6_LRS
 select SR.GEOM
 from STREETS_AND_RAILROADS SR
 where SR.ID = 56;

--c
select 
 SDO_GEOM.SDO_LENGTH(SR.GEOM, 1, 'unit=km') DISTANCE,
 ST_LINESTRING(SR.GEOM) .ST_NUMPOINTS() ST_NUMPOINTS
from A6_LRS SR, MAJOR_CITIES C
where SDO_RELATE(SR.GEOM,
 SDO_GEOM.SDO_BUFFER(C.GEOM, 10, 1, 'unit=km'),
'MASK=ANYINTERACT') = 'TRUE'
and C.CITY_NAME = 'Koszalin';

--d
UPDATE A6_LRS 
SET GEOM =  SDO_LRS.CONVERT_TO_LRS_GEOM(GEOM, 0, 276.681);

--e
INSERT INTO USER_SDO_GEOM_METADATA
VALUES ('A6_LRS','GEOM',
MDSYS.SDO_DIM_ARRAY(
 MDSYS.SDO_DIM_ELEMENT('X', 12.603676, 26.369824, 1),
 MDSYS.SDO_DIM_ELEMENT('Y', 45.8464, 58.0213, 1),
 MDSYS.SDO_DIM_ELEMENT('M', 0, 300, 1) ),
 8307);
 
 --f
CREATE INDEX lrs_a6_idx ON A6_LRS(GEOM) INDEXTYPE IS MDSYS.SPATIAL_INDEX;

--zad2
select SDO_LRS.VALID_MEASURE(GEOM, 500) VALID_500
from A6_LRS;

--b
select
 SDO_LRS.GEOM_SEGMENT_END_PT(GEOM) END_PT
from A6_LRS;

--c
select SDO_LRS.LOCATE_PT(GEOM, 150, 0) KM150 from A6_LRS;

--d
select SDO_LRS.CLIP_GEOM_SEGMENT(GEOM, 120, 160) CLIPED from A6_LRS;

--e
select SDO_LRS.get_next_shape_pt(A6.GEOM, C.GEOM) WJAZD_NA_A6
from A6_LRS A6, MAJOR_CITIES C where C.CITY_NAME = 'Slupsk';

--f
select SDO_LRS.GEOM_SEGMENT_LENGTH(SDO_LRS.OFFSET_GEOM_SEGMENT(A6.GEOM, M.DIMINFO, 50, 200, 50,
 'unit=m arc_tolerance=1')) /1000 dlugosc
from A6_LRS A6, USER_SDO_GEOM_METADATA M
where M.TABLE_NAME = 'A6_LRS' and M.COLUMN_NAME = 'GEOM';


